#!/usr/bin/env python

import sys
import re

######################################################################
# Read the configuration file
#######################################################################
config_file = open(sys.argv[1])

LOGFILE_START_STATEMENT = re.compile('^LOGFILE: (.*)$')



file_monitor_conditions = {}

for line in config_file.readline():
    re
    
