#!/usr/bin/python

import os
import sys


if os.name == 'posix':
    # yay!  we're unix.  Piece of cake...
    all_filesystems = ["/","/var","/tmp","/home"]
    for fs in all_filesystems:
        (bsize, frsize, blocks, bfree, bavail, files, ffree, favail, flag, namemax) = (os.statvfs(fs)

elif os.name == ' ':
